services:
  web:
    build: .
    container_name: convad-web
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    environment:
      - DEBUG_KEYWORDS=${DEBUG_KEYWORDS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}

    command: npm run dev
